#!/usr/bin/python3

import os
import sys


HOME = os.environ['HOME']
CWD = os.getcwd()


def mklink(src, dest):
    print('Creating link to %s at %s' % (src, dest))
    if os.path.lexists(dest):
        os.remove(dest)
    os.symlink(src, dest)


def mkdir(dest):
    print('Creating directory %s' % dest)
    os.mkdir(dest)


def mklinks(src, dest):
    if not os.path.exists(dest):
        mkdir(dest)

    for filename in os.listdir(src):
        linksrc = os.path.join(src, filename)
        linkdest = os.path.join(dest, filename)
        if os.path.isdir(linksrc):
            mklinks(linksrc, linkdest)
        else:
            mklink(linksrc, linkdest)


if __name__ == '__main__':
    targets = sys.argv[1:]
    for target in targets:
        print('... linking files in %s...' % (target))
        mklinks(os.path.join(CWD, target), HOME)
