#!/usr/bin/python3

import argparse
import os


HOME = os.environ['HOME']
CWD = os.getcwd()
SHARED = os.path.join(CWD, 'shared')

parser = argparse.ArgumentParser()
parser.add_argument('--source')
parser.add_argument('--verbose', action='store_true')
parser.add_argument('--dry', action='store_true')
args = parser.parse_args()


def mklink(src, dest):
    if args.dry:
        print('Would make link to %s at %s' % (src, dest))
        return
    if args.verbose:
        print('Creating link to %s at %s' % (src, dest))
    if os.path.exists(dest):
        os.remove(dest)
    os.symlink(src, dest)


def mkdir(dest):
    if args.dry:
        print('Would create directory %s' % dest)
        return
    if args.verbose:
        print('Creating directory %s' % dest)
    os.mkdir(dest)


def mklinks(src, dest):
    if not os.path.exists(dest):
        mkdir(dest)

    if args.verbose:
        print('Making links for directory %s' % src)
    for filename in os.listdir(src):
        fullpath = os.path.join(src, filename)
        target = os.path.join(dest, filename)
        if os.path.isdir(fullpath):
            mklinks(fullpath, target)
        else:
            mklink(fullpath, target)

if __name__ == '__main__':
    mklinks(SHARED, HOME)
    if args.source:
        mklinks(os.path.join(CWD, args.source), HOME)
