#! /usr/bin/env bash

# Set up virtualenvs for nvim
py2_version="2.7.16"
py3_version="3.8.1"

pyenv install "$py2_version"
pyenv install  "$py3_version"

pyenv virtualenv "$py2_version" neovim2
pyenv virtualenv "$py3_version" neovim3

## The following needs to be run manually:
#
# pyenv activate neovim2
# pip install neovim
#
# pyenv activate neovim3
# pip install neovim
# pip install flake8
# pip install black
# pip install mypy
