#!/bin/sh

MONITOR_LIST=$(xrandr --listmonitors | sed '1 d' | awk 'NF>1{print $NF}')

killall polybar 2> /dev/null

for mon in $MONITOR_LIST; do
  echo "Launching on monitor $mon"
  env MONITOR=$mon polybar top &
done
# '-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1'
