#!/bin/bash

MONITOR_LIST=("$(xrandr --query | awk '/.* connected.*/ {print $1}')")
NUM_MONITORS=${#MONITOR_LIST[@]}

feh --randomize --bg-fill "$HOME/Pictures/walls/*.png"

if [[ "$NUM_MONITORS" -eq 1 ]]; then
    bspc monitor "${MONITOR_LIST[0]}" -d I II III IV V VI VII VIII IX X
elif [[ "$NUM_MONITORS" -eq 2 ]]; then
    bspc monitor "${MONITOR_LIST[0]}" -d I II III IV V
    bspc monitor "${MONITOR_LIST[1]}" -d VI VII VIII IX X
fi

sxhkd &

echo "${MONITOR_LIST[@]}" >> bspc.log

bash "$HOME/.config/polybar/barlauncher" &

bspc config border_width         4
bspc config window_gap           8

bspc config normal_border_color '#333'
bspc config active_border_color '#333'
bspc config focused_border_color '#6A6'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
