return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"cpp",
			"css",
			"diff",
			"dockerfile",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"go",
			"javascript",
			"json",
			"html",
			"lua",
			"luadoc",
			"markdown",
			"mermaid",
			"ocaml",
			"prisma",
			"python",
			"rust",
			"sql",
			"terraform",
			"tmux",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
		},
		auto_install = true,
		highlight = {
			enable = true,
		},
		indent = {
			enable = true,
		},
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<leader>v",
				scope_incremental = "<leader>vs",
				node_incremental = "<leader>vi",
				node_decremental = "<leader>vd",
			},
		},
	},
	config = function(_, opts)
		vim.highlight.priorities.semantic_tokens = 95
		require("nvim-treesitter").setup(opts)
	end,
}
